In [33]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [41]:
from modules.NaiveBayesClassifier import train_NBC, get_predict_probs_NBC, predict_NBC
from modules.MixtureModels import get_probabilities_mixture_models, predict_mixture_models
import modules.directional_change as dc
import numpy as np
import pandas as pd

In [12]:
'''Testing Code for Naive Bayes Classifier'''
n = 50 # Samples
N = 3 # Dimensions
K = 2 # Classes

X = np.random.normal(size=(n,N))
y = np.random.randint(K, size=n)

model = train_NBC(X, y)

In [22]:
X_test = np.random.normal(size=(5,N))
probs = get_predict_probs_NBC(model, X_test)

In [23]:
probs

array([[0.51606893, 0.48393107],
       [0.46321459, 0.53678541],
       [0.57658988, 0.42341012],
       [0.43027957, 0.56972043],
       [0.42692204, 0.57307796]])

In [24]:
'''Testing the mixture models'''

X = np.random.normal(size=(n,N))
y = np.random.randint(K, size=n)
model1 = train_NBC(X, y)

X = np.random.normal(size=(n,N))
y = np.random.randint(K, size=n)
model2 = train_NBC(X, y)

X = np.random.normal(size=(n,N))
y = np.random.randint(K, size=n)
model3 = train_NBC(X, y)


In [20]:
X_test = np.random.normal(size=(5,N))
q = np.array([25,25,50])

In [25]:
probs1 = get_predict_probs_NBC( model1, X_test )
probs2 = get_predict_probs_NBC( model2, X_test )
probs3 = get_predict_probs_NBC( model3, X_test )


In [26]:
probs1

array([[0.71010633, 0.28989367],
       [0.5006721 , 0.4993279 ],
       [0.92314909, 0.07685091],
       [0.47173046, 0.52826954],
       [0.42256039, 0.57743961]])

In [27]:
probs2

array([[0.39650229, 0.60349771],
       [0.21439352, 0.78560648],
       [0.04240097, 0.95759903],
       [0.41970178, 0.58029822],
       [0.37523777, 0.62476223]])

In [28]:
probs3

array([[0.22771961, 0.77228039],
       [0.68895389, 0.31104611],
       [0.87336345, 0.12663655],
       [0.3584467 , 0.6415533 ],
       [0.43377572, 0.56622428]])

In [39]:
get_probabilities_mixture_models(([probs1, probs2, probs3]), q)

array([[0.39051196, 0.60948804],
       [0.52324335, 0.47675665],
       [0.67806924, 0.32193076],
       [0.40208141, 0.59791859],
       [0.4163374 , 0.5836626 ]])

In [45]:
'''Testing trading startegy'''
data = dc.get_data(['^GSPC'], '2010-01-01', 6.5)
theta = 0.075

[*********************100%***********************]  1 of 1 completed


In [47]:
d2 = dc.get_dc_data_v2( data, theta)

In [49]:
d2.__len__()

38

In [50]:
d2[0]

(Timestamp('2010-02-04 00:00:00'),
 1063.1099853515625,
 Timestamp('2010-01-19 00:00:00'),
 1150.22998046875)

In [87]:
d1 = dc.get_DC_data(data, 0.075)

In [88]:
d1

[(Timestamp('2020-03-09 00:00:00'),
  2746.56005859375,
  Timestamp('2020-03-05 06:30:00'),
  3075.699951171875),
 (Timestamp('2020-03-13 00:00:00'),
  2711.02001953125,
  Timestamp('2020-03-12 00:00:00'),
  2480.639892578125),
 (Timestamp('2020-03-16 00:00:00'),
  2386.1298828125,
  Timestamp('2020-03-13 00:00:00'),
  2711.02001953125),
 (Timestamp('2020-03-24 00:00:00'),
  2447.330078125,
  Timestamp('2020-03-23 00:00:00'),
  2237.39990234375)]

In [99]:
TMV = dc.get_TMV(d1, theta)
TMV

2020-03-12   -2.579619
2020-03-13    1.238283
2020-03-23   -2.329358
dtype: float64

In [100]:
T = dc.get_T( d1 )
T

2020-03-12     6.708333
2020-03-13     1.000000
2020-03-23    10.000000
dtype: float64

In [101]:
R = dc.get_R( TMV, T, theta )
R

2020-03-12   -0.028840
2020-03-13    0.092871
2020-03-23   -0.017470
dtype: float64

In [102]:
1.238283 * 0.075

0.092871225